

//User Profile
export const SET_LOGGED_IN_USER_INFO = "SET_LOGGED_IN_USER_INFO";
export const SET_USER_ROLES = "SET_USER_ROLES";

//Materials Lookups
export const SET_MATERIALS = "SET_MATERIALS";
export const SORT_MATERIALS = "SORT_MATERIALS";
export const SET_SELECTED_MATERIALS = "SET_SELECTED_MATERIALS";
export const SET_GROUP_SELECTED_MATERIALS = "SET_GROUP_SELECTED_MATERIALS";
export const RESET_SELECTED_MATERIALS = "RESET_SELECTED_MATERIALS";
export const SET_LOADING_MATERIALS = "SET_LOADING_MATERIALS";
export const FILTER_MATERIALS = "FILTER_MATERIALS";
export const RESET_CURRENT_MATERIALS = "RESET_CURRENT_MATERIALS";
export const UPDATE_CURRENT_MATERIAL = "UPDATE_CURRENT_MATERIAL";
export const SET_DEVICE_CONFIG = "SET_DEVICE_CONFIG";
export const UPDATE_ALL_MATERIALS = "UPDATE_ALL_MATERIALS";
export const UPDATE_ACTIVE_WELLS = "UPDATE_ACTIVE_WELLS";
export const SET_GROUPING_MATERIALS = "SET_GROUPING_MATERIALS";








//Strains Lookups
export const SET_STRAINS = "SET_STRAINS";


//Roles
export const SET_SYSTEM_ROLES = "SET_SYSTEM_ROLES";





